### ISSUE TITLE
super small issues

### ISSUE THREAD

**Issue by zacharyyamaoka** [mjbots/moteus_ros2#1]
![image](https://github.com/user-attachments/assets/10a617ef-3804-49c2-92cf-ea389fc58829)

Very small issues in README

ros2 topic pub /moteus/id_1/cmd_position moteus_msgs/msg/PositionCommand "{position: [0.5], accel_limit: [5], watchog_timeout:[.NAN]}"

watchog_timeout I think should be watchdog_timeout (missing a d)

**Comment by jpieper** [comment]
Fixed in 3d0f85b1da775094cfd08a6891d53864eaea47fd

Thanks!
